name: Create main release pull request
on:
  push:
    branches:
      - releases
jobs:
  mainReleases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: releases
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: releases
          base: main
